# Generated by Django 6.0.5 on 2026-06-08 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0005_interviewquestion_reference_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewquestion',
            name='generation_source',
            field=models.CharField(blank=True, default='curated', help_text='csv | curated | dataset | ml_guided | dynamic', max_length=20),
        ),
    ]
