# Generated by Django 6.0.5 on 2026-05-27 00:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='profileunlock',
            name='unique_employer_candidate_unlock',
        ),
        migrations.AlterUniqueTogether(
            name='profileunlock',
            unique_together={('employer', 'candidate')},
        ),
    ]
