# Generated by Django 6.0.5 on 2026-06-05 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_phone_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='interview_cooldown_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='quiz_cooldown_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
